# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14e7ee4a6a8fbce49232b0efb51e5c06b7c27f3a9bebea8e7dd92f93885fb29cee08f351680646139ba0465277aea73f1ca06ee0314e4bc71b02cf07ad3ecfb4

test:
  secret_key_base: 0219a12bada759ee6ac0a4c719b604b19abaa406df68b24eb4f9e432fbcfd6eacb131e09596efcde3a960da0b7a3924aeed45e94eb50984222265a630859b6d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
